### ISSUE TITLE
URL parsing issue

### ISSUE THREAD

**Issue by emmjam** [deepjyoti30/ytmdl#219] opened 2022-02-18 10:02 UTC
Youtube has changed the url format, and now urls are in this format: https://www.youtube.com/watch?app=desktop&v=Y2_CNGOx2A8
Currently the app reformats this as https://www.youtube.com/watch?app=desktop, which is wrong. 
It should drop the "app=desktop&", so that the URL is interpreted as https://www.youtube.com/watch?v=Y2_CNGOx2A8

Thanks

**Comment by deepjyoti30** [comment] 2022-03-08 16:51
@emmjam Thanks for pointing this out.

Could you tell me where you are getting the URL from? Is it from the share menu? Or is it directly from the website URL bar?

I can see that in the website, their URL's are still the old format.

Anyhow, I would like to consider this edge case.

**Comment by deepjyoti30** [comment] 2022-03-09 14:57
@emmjam Can you provide a way to reproduce this issue? It's not clear if you're referring to passing the url with `--url` or just passing the URL in the song name?

If this is a`ytmdl-web` issue, I will transfer this to that repo.

**Comment by deepjyoti30** [comment] 2022-03-09 15:08
@emmjam Closing for now since I cannot reproduce the issue.

As I said, if the issue is in the web, you should open an issue at [ytmdl-web](https://github.com/deepjyoti30/ytmdl-web-v2)

If you still see this issue in the CLI, you can reopen this issue with steps to reproduce.

Moreover the referenced commit fixes the only possible location I saw this issue possibly occurring in.

**Closed by deepjyoti30** 2022-03-09 15:08 UTC
