### ISSUE TITLE
Download fails while searching for metadata

### ISSUE THREAD

**Issue by mrmeszaros** [deepjyoti30/ytmdl#122] opened 2020-11-20 10:18 UTC
# Bug report

## Checklist

- [X] I have searched for similar bugs in the issues.
- [X] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2020.11.20-1`
- Youtube-dl version: `2020.09.20`

## How Ytmdl was installed?

Installed via pip

## Console Log

```console
mrmeszaros@big-della ~> ytmdl "Abigél Musical - Hazatér a sok hős" --level DEBUG
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=['Abigél Musical - Hazatér a sok hős'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url=None)
 ==>  ['Abigél Musical - Hazatér a sok hős']
 ==>  Abigél Musical - Hazatér a sok hős
 ==>  Searching to see if already present in /home/mrmeszaros/Music
 ==> Abigél Musical - Hazatér a sok hős found.
Do you still want to continue[y/n]y
 ==>  proxy passed: None
 ==>  Passed format: mp3
 ==>  Searching Youtube for Abigél Musical - Hazatér a sok hős
 ==> Choose One (One with [M] is verified music)
 [1] Abigél Musical - Hazatér a sok hős  (Part 15) by Drsuni with dur 3:28
 [2] Abigél Hazatér a sok hős by emeriko2222 with dur 2:40
 [3] Abigél I.-II. rész by Frozen Hell with dur 2:18:22
 [4] Somogyi Szilárd-Kocsák Tibor-Miklós Tibor: Abigél (musical) by Karantén színház with dur 2:34:06
 [5] Abigél Musical - Tiszta jellem ( Part 18 ) by Drsuni with dur 5:52
 [0] More results
 ==> Enter Choice [default is 1]
 ==>  {'title': 'Abigél Musical - Hazatér a sok hős  (Part 15)', 'href': '/watch?v=yYZkFMbu6AE', 'author_name': 'Drsuni', 'duration': '3:28', 'verified_music': False}
 ==>  Downloading Abigél Musical - Hazatér a sok hős  (Part 15) in 320kbps
 ==>  Saving the files to: /home/mrmeszaros/.cache/ytmdl
 ==>  /home/mrmeszaros/.cache/ytmdl/Abigél#Musical#-#Hazatér#a#sok#hős##(Part#15).mp3
3 MB   | 4 Mb/s || ETA: 5 s                                                                                                                                                             |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==>  Downloaded!
 ==>  Converting to mp3...
File '/home/mrmeszaros/.cache/ytmdl/Abigél#Musical#-#Hazatér#a#sok#hős##(Part#15).mp3_new.mp3' already exists. Overwrite ? [y/N] y
 ==>  Skip Meta: False
 ==>  Getting song data for Abigél Musical - Hazatér a sok hős...
 ==>  No results found with the keyword Abigél Musical - Hazatér a sok hős
Traceback (most recent call last):
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/ytmdl/metadata.py", line 30, in get_from_itunes
    SONG_INFO = itunespy.search_track(SONG_NAME)
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/itunespy/__init__.py", line 107, in search_track
    return search(term, country, 'music', entities['song'], attribute, limit)
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/itunespy/__init__.py", line 56, in search
    raise LookupError(search_error + str(term))
LookupError: No results found with the keyword Abigél Musical - Hazatér a sok hős

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrmeszaros/.local/bin/ytmdl", line 469, in <module>
    extract_data()
  File "/home/mrmeszaros/.local/bin/ytmdl", line 464, in extract_data
    main(args)
  File "/home/mrmeszaros/.local/bin/ytmdl", line 384, in main
    TRACK_INFO = metadata.SEARCH_SONG(song_metadata, filters=[args.artist, args.album])
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/ytmdl/metadata.py", line 170, in SEARCH_SONG
    data_provider = GET_METADATA_ACTIONS.get(
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/ytmdl/metadata.py", line 33, in get_from_itunes
    _logger_provider_error(e, 'iTunes')
  File "/home/mrmeszaros/.local/lib/python3.8/site-packages/ytmdl/metadata.py", line 23, in _logger_provider_error
    ".format(name, logger.get_log_file()))
AttributeError: 'Logger' object has no attribute 'get_log_file'
```

## Description

It seems to me that ytmdl cannot find the logger to log the error message related to a song without metadata in iTunes.

**Comment by deepjyoti30** [comment] 2020-11-20 14:17
@mrmeszaros Thanks for the report. The issue is from the logger being used. In this version, ytmdl has started using `simber` as a logger and hence this issue. I will add a fix for this asap.

**Comment by deepjyoti30** [comment] 2020-11-20 14:29
Should be fixed now. Just update the logger in one of the following way.

If you installed from **pypi**:

```console
pip install simber --upgrade
```

If you installed from **AUR**:

```console
yay -S simber
```

**Comment by mrmeszaros** [comment] 2020-11-20 20:34
Thanks, it worked!

**Comment by mrmeszaros** [comment] 2020-11-21 00:34
Somehow the missing metadata still breaks the download process:

- The process ends with an error, and the song does not get copied to the `~/Music` folder
- I was able to circumvent the problem by passing the `--skip-meta` option
- I think that failing to find metadata for a song should not stop the process, or have it logged too:

```console
mrmeszaros@big-della ~> ytmdl "Abigél himnusz" --level DEBUG
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=['Abigél himnusz'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url=None)
 ==>  ['Abigél himnusz']
 ==>  Abigél himnusz
 ==>  Searching to see if already present in /home/mrmeszaros/Music
 ==>  proxy passed: None
 ==>  Passed format: mp3
 ==>  Searching Youtube for Abigél himnusz
 ==> Choose One (One with [M] is verified music)
 [1] AbigélAbigél himnusz by bartusmarcsi with dur 3:55
 [2] Abigél - Abigél himnusz by 39 Jano with dur 3:44
 [3] Abigél himnusz(Vágó Zsuzsi,Szendy Szilvi,Csonka András,Peller Anna,Nádasi Veronika) by dijjja8 with dur 3:53
 [4] Abigél I.-II. rész by Frozen Hell with dur 2:18:22
 [5] Abigél-Szent Karácsony by bartusmarcsi with dur 4:49
 [0] More results
 ==> Enter Choice [default is 1]
 ==>  {'title': 'AbigélAbigél himnusz', 'href': '/watch?v=pfN5zBxNsus', 'author_name': 'bartusmarcsi', 'duration': '3:55', 'verified_music': False}
 ==>  Downloading AbigélAbigél himnusz in 320kbps
 ==>  Saving the files to: /home/mrmeszaros/.cache/ytmdl
 ==>  /home/mrmeszaros/.cache/ytmdl/AbigélAbigél#himnusz.mp3
4 MB   | 6 Mb/s || ETA: 5 s                                                                                                                                                             |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==>  Downloaded!
 ==>  Converting to mp3...
File '/home/mrmeszaros/.cache/ytmdl/AbigélAbigél#himnusz.mp3_new.mp3' already exists. Overwrite ? [y/N] y
 ==>  Skip Meta: False
 ==>  Getting song data for Abigél himnusz...
 ==>  No results found with the keyword Abigél himnusz
 ==>  Something went wrong with iTunes. The program will continue withthe other providers. Please check 'None' for more details.
 ==>  No data was found!
```

**Comment by deepjyoti30** [comment] 2020-11-21 07:58
@mrmeszaros This is a known issue. Since half og the apps functionality is to save metadata automatically, that is why it breaks. If the song was to be copied even if meta was not found, it would just be a song with no proper file name etc which is basically the equivalent of using `youtube-dl`.

This is why it stops working when no meta is found.

**Comment by mrmeszaros** [comment] 2020-11-21 08:08
@deepjyoti30 Thanks for the reply!

Would You mind extending the final log message to say something about it?

Like an error: ` ==> Withholding file because of missing song data`.

And then maybe an info: `Use --skip-meta to silence this error, or provide song meta via the --title --album --artist flags`

**Comment by deepjyoti30** [comment] 2020-11-23 11:49
@mrmeszaros Sure. I think that message would be a nice addition.!

**Comment by mrmeszaros** [comment] 2020-11-23 11:53
@deepjyoti30 I can make a PR if You do not mind🙂

**Comment by deepjyoti30** [comment] 2020-11-23 11:57
@mrmeszaros Sure. Just make sure you read the Contribution guidelines before that. Also, make the PR to the unstable branch.

Since this release, I'm aiming to continue the development in that branch and only merge to master if the feature is tested and working!

**Comment by deepjyoti30** [comment] 2020-12-09 12:41
@mrmeszaros Are you going to make the PR? I think I can go ahead and make the changes.

**Comment by mrmeszaros** [comment] 2020-12-11 10:11
Hey @deepjyoti30 - sorry for taking so long - I have been looking into it, and thinking about it.

The [Simber](https://github.com/deepjyoti30/simber) logger halts the program execution on a critical message.
Therefore, it seems to me that setting the exit code would have to be changed there.

On the other hand, it is usually not the loggers responsibility to manipulate program flow (https://stackoverflow.com/a/31170408/3887137).

But it could be added as an option:
```python
logger = Logger(exit_on_critical=True)
```

**Comment by deepjyoti30** [comment] 2020-12-11 14:47
@mrmeszaros Can't we just change the critical message to error and add subsequent error messages and then a critical message?

**Comment by mrmeszaros** [comment] 2020-12-11 16:05
@deepjyoti30 that is half of the part - I wanted to add the non zero exit code too, and got hung up on that, and am currently rebasing my changes with the new exception classes.

BTW, do You have any idea why cannot I test my changes? when I run, it says, it cannot find the exceptions module (although it is there):

```
mrmeszaros@big-della ~/P/ytmdl (unstable)> bin/ytmdl --level DEBUG selective attenction test
Traceback (most recent call last):
  File "bin/ytmdl", line 30, in <module>
    from ytmdl.exceptions import (
ModuleNotFoundError: No module named 'ytmdl.exceptions'
```

**Comment by deepjyoti30** [comment] 2020-12-14 04:25
@mrmeszaros It might be that another version of ytmdl is present which is why you're not able to test the latest code.

Consider uninstalling ytmdl from your package manager, for eg in Arch Linux `yay -R ytmdl`. Once it is removed.

Uninstall using pip `pip uninstall ytmdl`. Keep doing the `pip` command until it shows that no ytmdl is present.

After that check if all the installed versions are installed by running `ytmdl` in the cli. It should give you an error.

Once, that's done, install the latest changes from your directory using `python setup.py install`. Verify the version as well using `pip freeze | grep -i ytmdl` as well as `ytmdl --version`.

It should work after that.

**Comment by deepjyoti30** [comment] 2020-12-14 04:38
@mrmeszaros Regarding the exit code issue. I think I will add an optional param to the `critical` method that would allow the user to pass  the desired exit code.

**Comment by deepjyoti30** [comment] 2021-01-13 13:15
Fixed in the latest release

**Closed by deepjyoti30** 2021-01-13 13:15 UTC
Labels: bug

**Comment by blcarson** [comment] 2021-02-01 12:49
Still seeing this error on songs when metadata can't be found. The `--skip-meta` still does the trick as a workaround but I end up having to watch to see if it fails first and then rerun the command with that flag.

**Comment by deepjyoti30** [comment] 2021-02-01 14:29
@blcarson This shouldn't happen, especiall in the latest version. Can you share the version of the following:

`ytmdl`: Use `ytmdl --version`
`simber`: Use `pip freeze | grep -i simber`

**Comment by blcarson** [comment] 2021-02-02 04:12
`ytmdl: 2021.01.14-1`

second command produced:

```
WARNING: Could not generate requirement for distribution -tmdl 2021.1.14.post1 (/usr/local/lib/python3.9/site-packages): Parse error at "'-tmdl==2'": Expected W:(abcd...)
simber==0.2.1
```

**Comment by deepjyoti30** [comment] 2021-02-02 04:33
@blcarson The versions seem all right. Are you sure it is the same error? In the latest versions the issue should be fixed, it was just a call to a method in the `logger` object that was failing. I fixed it in the next release after realising of this issue.

Can you perhaps share the logs?

**Comment by blcarson** [comment] 2021-02-02 05:53
```
ytmdl https://www.youtube.com/watch\?v\=P3aGk_Gwqjw --level DEBUG          
 ==> Logger running in DEBUG mode 
 ==> Passed args: Namespace(SONG_NAME=['https://www.youtube.com/watch?v=P3aGk_Gwqjw'], quiet=False, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, disable_sort=False, proxy=None, url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False) 
 ==> ['https://www.youtube.com/watch?v=P3aGk_Gwqjw'] 
 ==> https://www.youtube.com/watch?v=P3aGk_Gwqjw 
 ==> Searching to see if already present in /Users/brandon/Downloads 
 ==> proxy passed: None 
 ==> Passed format: mp3 
 ==> Searching Youtube for https://www.youtube.com/watch?v=P3aGk_Gwqjw 
 ==> Choose One (One with [M] is verified music)
 [1] The Lone Slim Shady - Caravan Palace vs. Eminem (Mashup) by oneboredjeu Mashup with dur 4:16
 [2] The Lone Slim Shady (Explicit) - Caravan Palace vs. Eminem (Mashup) by HellJustFroze with dur 4:16
 [3] Kayuun - A Fortnite Reverse Montage by Kayuun with dur 5:33
 [4] KILLING TWITCH STREAMERS W/ REACTIONS! (TSM Daequan, JenaUrf, StDx Vide...) by lyr1c with dur 3:43
 [5] LONE SLIM SHADY - Fortnite Montage (xbox only) by XmhUK with dur 4:20
 [0] More results
 ==> Enter Choice (1): 1
 ==> Downloading The Lone Slim Shady - Caravan Palace vs. Eminem (Mashup) in 320kbps 
 ==> Saving the files to: /Users/brandon/.cache/ytmdl 
 ==> /Users/brandon/.cache/ytmdl/The#Lone#Slim#Shady#-#Caravan#Palace#vs.#Eminem#(Mashup).mp3 
4 MB   | 942 Kb/s || ETA: 1 s                           |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded! 
 ==> [{}] 
 ==> song_name:  The Lone Slim Shady - Caravan Palace vs. Eminem (Mashup)  song_meta:  https://www.youtube.com/watch?v=P3aGk_Gwqjw
 ==> None:None 
 ==> Skip Meta: False 
 ==> Getting song data for https://www.youtube.com/watch?v=P3aGk_Gwqjw... 
 ==> No metadata found for `https://www.youtube.com/watch?v=P3aGk_Gwqjw` . Pass `--ignore-errors` to ignore this.
```

**Comment by deepjyoti30** [comment] 2021-02-02 12:04
@blcarson The issue here is not the same as what @mrmeszaros raised. His issue was being raised because of language related constraints, which is why he got this error.

In your case, it is because the metadata is being searched by using the youtube URL. You need to pass the name of the song using the `--song` flag.

For eg: in this case:

```ytmdl https://www.youtube.com/watch\?v\=P3aGk_Gwqjw --song "Slim Shady"```

I think it would be good for everyone though to enable auto extraction of title from the passed youtube URL and searching using that. I will work on that.

**Comment by blcarson** [comment] 2021-02-04 15:02
OK thanks for the clarification, much appreciated.
