### ISSUE TITLE
Please implement fix to n-parameter challenge by youtube.

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [deepjyoti30/ytmdl#210] opened 2021-11-18 03:14 UTC
# Feature Request

## Checklist

- [ X] I've searched the bugtracker for similar feature requests including closed ones.
- [ X] I will add the enhancement label to the issue.

## Description
I believe yt-mdl use youtube-dl under the hood, and downloads as I observe are very slow, about 40-75KBps on a 10MBps connection. 
I don't know if you are aware of this, but youtube has throttled download speeds to non-player clients, by sending them a parameter and asking to compute something based on it, if they don't the speed will be throttled, [youtube-dl](https://github.com/ytdl-org/youtube-dl/pull/30184) has a detailed information on this. There has been many pulls but none of the has been committed, [yt-dlp](https://github.com/yt-dlp/yt-dlp), on the other hand implemented the fix.

I request you to take a look into this.

Thanks and regards.

**Comment by deepjyoti30** [comment] 2021-11-18 14:51
@SisyphusIsntHappy Thanks for raising this request. I will take a look. I have indeed noticed the slower download speeds and I kind of thought it was an youtube-dl issue. I will see what can be done regarding that!

**Comment by deepjyoti30** [comment] 2021-11-19 05:24
@SisyphusIsntHappy I took a look at the issue. I can see that YouTube is now randomly trying to slow down simultaneous downloads by using that n-parameter challenge.

The issue is that `ytmdl` uses `youtube-dl` under the hood to download the songs. It itself doesn't handle any part of the download. The download is merely passed on to youtube-dl and it in return downloads the song.

This means that until `youtube-dl` doesn't add a fix for the issue, I cannot either.

One alternative would be to just move on to a separate framework for the downloads ( `ytdlp` ) but the issue with that is unreliability. I agree that that fork is doing great job but it is very young (not even an year old). This leads me to doubt whether the framework will be reliable in the long term. This is why at the moment I am skeptical to move away from `youtube-dl` as the core library and use something else.

I am considering other options like `pytube` that might be more reliable looking at thier release and commit history.

**Comment by deepjyoti30** [comment] 2021-11-19 13:46
@SisyphusIsntHappy Yes I am aware of spotify-dl. I actually did take a look at their source few months back and I think they do use pytube.

Also, as it turns out the issue for the n-param challenge is already fixed in pytube.

**Comment by deepjyoti30** [comment] 2021-12-18 05:44
Hi @SisyphusIsntHappy Seems like `youtube-dl` has added a fix for this and added a new release. This issue should be fixed with the released of youtube-dl 2021.12.17.

Do check and report back here if it's not fixed. On my end, it's fixed!

**Closed by deepjyoti30** 2021-12-18 05:44 UTC
Labels: enhancement

**Comment by deepjyoti30** [comment] 2022-01-30 10:40
@SisyphusIsntHappy I have made change in the source to make the move to `yt-dlp` since `youtube-dl` is not maintained anymore and `yt-dlp` has good support.

You can test it out by checking the `unstable` branch.

This commit adds the changes: 0eb0cb8
