### ISSUE TITLE
 ERROR: 'total_bytes'

### ISSUE THREAD

**Issue by Nasjoe** [deepjyoti30/ytmdl#60] opened 2020-04-24 12:58 UTC
Sometimes this append :

 ==> Searching to see if already present in /mnt/raidz/slaan/KonectRadio/Playlist/Jazz
 ==> Searching Youtube for https://www.youtube.com/watch?v=W_UfkT2BGlE
 ==> Choose One
 [1] Adrian Younge and Ali Shaheed Muhammad feat. Roy Ayers - "Synchronize Vibration" by Jazz Is Dead Official with dur 3:32
 ==> Enter Choice [a valid choice] 1
 ==> Downloading Adrian Younge and Ali Shaheed Muhammad feat. Roy Ayers - "Synchronize Vibration" in 320kbps
 ==> Saving the files to: home/user/.cache/ytmdl
 ==> 'total_bytes'
 ==> ERROR: 'total_bytes'

**Comment by deepjyoti30** [comment] 2020-04-24 14:30
@Nasjoe Let me look into it, it's thrown by youtube-dl that ytmdl uses to download the files, I'll have to reproduce and check what the issue is.

Thanks for reporting.

**Comment by deepjyoti30** [comment] 2020-04-24 14:44
@Nasjoe The issue was due to a dict value that was being tried to access while it wasn't present, should be fixed in 71d7b43

Closing now. You can test the latest commit and report back if you face it again.

**Closed by deepjyoti30** 2020-04-24 14:44 UTC
