### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by ucalyptus** [deepjyoti30/ytmdl#19] opened 2019-11-15 18:37 UTC
ytmdl new divide
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
 ==> Searching Youtube for new divide
 ==> Choose One
 [1] New Divide (Official Video) - Linkin Park by Linkin Park
 [2] New Divide [Live in Red Square 2011] - Linkin Park by Linkin Park
 [3] Linkin Park - New Divide (Lyrics) - GetThemLyrics by GetThemLyrics
 [4] Transformers 2 ( Linkin Park - New Divide ) [HD] by SylverJack
 [5] LINKIN PARK – NEW DIVIDE (Official Music Video) by Warner Music Germany
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading New Divide (Official Video) - Linkin Park in 320kbps
 ==> ERROR: list index out of range

**Comment by deepjyoti30** [comment] 2019-11-16 03:46
I think it's probably caused due to that warning you're getting. I'll try to fix it soon.

**Comment by rdrew** [comment] 2019-11-16 13:06
I'm getting the same error but I dont have the "RequestsDependencyWarning"

**Comment by deepjyoti30** [comment] 2019-11-16 13:08
@rdrew Can you tell me what song you're searching for. It might be song specific.

**Comment by rdrew** [comment] 2019-11-17 17:20
Same result for all song searchs

**Comment by deepjyoti30** [comment] 2019-11-18 03:10
@rdrew Can you try installing the latest commits from the repo and check. I seriously can't debug because I can't reproduce the issue.

**Comment by fabiocaccamo** [comment] 2019-11-18 14:08
I have this issue for all song searchs.

**Comment by deepjyoti30** [comment] 2019-11-20 10:42
Let me see if it is a Python 3.8 specific issue. I'm using 3.7

**Comment by rerenoob** [comment] 2019-11-23 05:10
I got a similar error. Here is the stack trace:

`  File "/Users/computer/virtualenv/ytmdl/bin/ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2019.11.15.post2', 'ytmdl')
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/EGG-INFO/scripts/ytmdl", line 220, in <module>
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/EGG-INFO/scripts/ytmdl", line 215, in extract_data
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/EGG-INFO/scripts/ytmdl", line 153, in main
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/ytmdl/yt.py", line 86, in dw
TypeError: print_exception() missing 2 required positional arguments: 'value' and 'tb'
`

**Comment by deepjyoti30** [comment] 2019-11-23 05:43
@rerenoob Hey, did you get the ```list index out of range``` issue? This stack trace is because of the traceback module which I was using to traceback but it doesn't point to what's causing the ```list index``` bug.

Can you please follow the following steps and give me the stack trace after that?

**I'm assuming you're using the clones version because the version is ```post-2``` one.**

- Replace the ```traceback.print_exception(e)``` line with ```traceback.print_exc()```
- Install again by running ```sudo python setup.py install``` in the root directory.
- Run ```ytmdl``` again with the same song name so that you face the same error.

Give me the traceback you get after doing the above steps.

**Comment by rerenoob** [comment] 2019-11-23 05:57
@deepjyoti30 I've done what you suggested and this is the traceback:
`Traceback (most recent call last):
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/ytmdl/yt.py", line 61, in dw
    url = get_youtube_streams(value)
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/ytmdl/yt.py", line 27, in get_youtube_streams
    url = stream_urls[1]
IndexError: list index out of range
 ==> ERROR: list index out of range
`

**Comment by deepjyoti30** [comment] 2019-11-23 06:00
@rerenoob Can you tell me what song you were searching for?

**Comment by rerenoob** [comment] 2019-11-23 06:08
@deepjyoti30 the same exception on any song I searched for. Here is an example:

```
(ytmdl) Sat Nov 23 - 00:03:33 @ ~/Projects/python/ytmdl [master]
☀️  ytmdl run to you dj doc
 ==> Searching to see if already present in /Users/computer/Music
 ==> Searching Youtube for run to you dj doc
 ==> Choose One
 [1] DJ DOC - Run To You by onejd with dur 3:54
 [2] DJ DOC - Run To You / I'm a Guy Like This / Summer Story / Dance with DOC [Yu Huiyeol's Sketchbook] by KBS World TV with dur 7:49
 [3] Classic Kpop - DJ DOC - Run To You + DL by ClassicKpop427 with dur 3:47
 [4] DJ Doc-Run To You Lyrics by kpopchop with dur 3:43
 [5] DJ DOC - Run to you, 디제이 디오씨 - 런투유, Music Camp 20000902 by MBCkpop with dur 3:18
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading DJ DOC - Run To You in 320kbps
Traceback (most recent call last):
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/ytmdl/yt.py", line 61, in dw
    url = get_youtube_streams(value)
  File "/Users/computer/virtualenv/ytmdl/lib/python3.7/site-packages/ytmdl-2019.11.15.post2-py3.7.egg/ytmdl/yt.py", line 27, in get_youtube_streams
    url = stream_urls[1]
IndexError: list index out of range
 ==> ERROR: list index out of range

```

**Comment by deepjyoti30** [comment] 2019-11-23 06:12
@rerenoob The bug is actually caused by ```youtube-dl```. When ytmdl is trying to extract the song's download url using ```youtube-dl -g <youtube URL>```, it is returning just one URL. I'm working on it currently.

**Comment by rerenoob** [comment] 2019-11-23 06:17
@deepjyoti30 when I changed `url = stream_urls[1]` to `url = stream_urls[0]`, it kinda worked, but I got another error:

```
(ytmdl) Fri Nov 22 - 23:52:49 @ ~/Projects/python/ytmdl [master]
☀️  ytmdl run to you dj doc
 ==> Searching to see if already present in /Users/computer/Music
 ==> Searching Youtube for run to you dj doc
 ==> Choose One
 [1] DJ DOC - Run To You by onejd with dur 3:54
 [2] DJ DOC - Run To You / I'm a Guy Like This / Summer Story / Dance with DOC [Yu Huiyeol's Sketchbook] by KBS World TV with dur 7:49
 [3] DJ Doc-Run To You Lyrics by kpopchop with dur 3:43
 [4] Classic Kpop - DJ DOC - Run To You + DL by ClassicKpop427 with dur 3:47
 [5] Big Bang - Run to you (DJ DOC) - 20071218 SBS Music Space by lumosx89 with dur 3:44
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading DJ DOC - Run To You in 320kbps
 ==> Saving the files to: /Users/computer/.cache/ytmdl
ERROR: unknown url type: ''
 ==> Downloaded!
 ==> Converting to mp3...
 ==> ERROR: [Errno 2] No such file or directory: '/Users/computer/.cache/ytmdl/DJ#DOC#-#Run#To#You.mp3'

```

**Comment by deepjyoti30** [comment] 2019-11-23 06:22
@rerenoob Usually when we run ```youtube-dl -g ``` we get two URL's. One is the video URL and the other is audio. So when you changed to ```stream_url[0]```, it should've been changed to the video URL, however in your case ```youtube-dl``` is returning nothing when we are trying to extract using ```-g``` flag and that's why the error ```unknown url type: ' '```.

Are you sure ```youtube-dl``` works for you??

**Comment by rerenoob** [comment] 2019-11-23 06:25
@deepjyoti30 Thanks for the explanation. I didn't know how `youtube-dl` worked. Never played with it, only through ytmdl. So no, I'm not sure if `youtube-dl` worked for me. I only assumed it worked from the output `==> Downloaded!`

**Comment by deepjyoti30** [comment] 2019-11-23 06:27
@rerenoob No, I mean can you try downloading some video using youtube-dl from the commandline?

```youtube-dl <URL>```. Pass the youtube video URL in place of the URL and tell me if it works.

**Comment by rerenoob** [comment] 2019-11-23 06:32
@deepjyoti30 I got some cert issue

```
(ytmdl) Sat Nov 23 - 00:04:10 @ ~/Projects/python/ytmdl [master]
☀️  youtube-dl https://www.youtube.com/watch?v=cENP3aul9lQ
[youtube] cENP3aul9lQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
```

**Comment by deepjyoti30** [comment] 2019-11-23 06:38
@rerenoob Can you try upgrading to the latest youtube-dl using ```sudo pip install --upgrade youtube-dl```

And then run the ```youtube-dl --no-check-certificate <URL>```

**Comment by rerenoob** [comment] 2019-11-23 06:44
@deepjyoti30 I could download with the `--no-check-certificate` flag. Here's the output:

```
(ytmdl) Sat Nov 23 - 00:41:12 @ ~/Projects/python/ytmdl [master]
☀️  syoutube-dl --no-check-certificate  https://www.youtube.com/watch?v=cENP3aul9lQ
[youtube] cENP3aul9lQ: Downloading webpage
[youtube] cENP3aul9lQ: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: DJ DOC - Run To You-cENP3aul9lQ.f133.mp4
[download] 100% of 4.40MiB in 00:01
[download] Destination: DJ DOC - Run To You-cENP3aul9lQ.f251.webm
[download] 100% of 3.69MiB in 00:00
[ffmpeg] Merging formats into "DJ DOC - Run To You-cENP3aul9lQ.mkv"
Deleting original file DJ DOC - Run To You-cENP3aul9lQ.f133.mp4 (pass -k to keep)
Deleting original file DJ DOC - Run To You-cENP3aul9lQ.f251.webm (pass -k to keep)
```

**Comment by deepjyoti30** [comment] 2019-11-23 06:49
@rerenoob That's exactly what we are looking for. The error was being caused by ```youtube-dl``` because of checking the certificate.

I've pushed the changes. Please clone the repo, install and see if it's working now. It
should be.

**Comment by rerenoob** [comment] 2019-11-23 17:51
@deepjyoti30 I recloned, reinstalled, and reran ytmdl for the same song. Here is the error I got:

```
(ytmdl) Sat Nov 23 - 11:37:33 @ ~/Projects/python/ytmdl [master]
☀️  ytmdl run to you dj doc
 ==> Searching to see if already present in /Users/computer/Music
 ==> Searching Youtube for run to you dj doc
 ==> Choose One
 [1] DJ DOC - Run To You by onejd with dur 3:54
 [2] DJ DOC - Run To You / I'm a Guy Like This / Summer Story / Dance with DOC [Yu Huiyeol's Sketchbook] by KBS World TV with dur 7:49
 [3] DJ Doc-Run To You Lyrics by kpopchop with dur 3:43
 [4] Classic Kpop - DJ DOC - Run To You + DL by ClassicKpop427 with dur 3:47
 [5] Big Bang - Run to you (DJ DOC) - 20071218 SBS Music Space by lumosx89 with dur 3:44
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading DJ DOC - Run To You in 320kbps
 ==> Saving the files to: /Users/computer/.cache/ytmdl
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
```

**Comment by deepjyoti30** [comment] 2019-11-23 17:56
@rerenoob The error you are facing is still because of the certificate thing.

This time it is downlaoder-cli that's not able to verify the certificate, I'll have to add a fix for that. I'll do that soon.

Thanks for the erros. I'll try to fix and get back to you soon.

**Comment by deepjyoti30** [comment] 2020-02-07 14:06
Should be fixed in upcoming release.

**Closed by deepjyoti30** 2020-02-07 14:06 UTC
