### ISSUE TITLE
Cant perform query with `+` 

### ISSUE THREAD

**Issue by Jipok** [deepjyoti30/ytmdl#265] opened 2023-03-27 13:41 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2023.02.28`
- Yt-dlp version: `2023.03.04`

## How Ytmdl was installed?

Via xbps package manager(void linux)

## Console Log

`ytmdl --level DEBUG --skip-meta -o . "ЗВУК УТКА КРЯКВА + СЕРАЯ"`
```console
==> Logger running in DEBUG mode
 ==> Passed args: Namespace(SONG_NAME=['ЗВУК УТКА КРЯКВА + СЕРАЯ'], quiet=False, output_dir='.', song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=True, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy=None, url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, ytdl_config=None, dont_transcode=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False)
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> ['ЗВУК УТКА КРЯКВА + СЕРАЯ']
 ==> verify title:  False
 ==> ЗВУК УТКА КРЯКВА + СЕРАЯ
 ==> None
 ==> Searching to see if already present in .
 ==> proxy passed: None
 ==> Passed format: mp3
 ==> Searching Youtube for ЗВУК УТКА КРЯКВА + СЕРАЯ
 ==> No search results found!
 ==> No song found. Please try again with a different keyword.
```

## Description

If I remove the plus then it finds the right one. Although there is a plus in the title.

**Comment by Jipok** [comment] 2023-03-27 13:44
Also for some reason it shows the duration is always 1 second more than on YouTube. Example:
7:03 on youtube, 7:04 in console
https://www.youtube.com/watch?v=WaTFKVEp9_A
![screenshot](https://user-images.githubusercontent.com/25588359/227956511-73ebebb5-7154-49a9-a391-9bb58fb248f2.png)

**Comment by deepjyoti30** [comment] 2023-04-29 14:12
> If I remove the plus then it finds the right one. Although there is a plus in the title.

This might be because of how youtube provides search where it accepts the search query through query params in the URL. This makes `+` a space though that should not lead to 0 results. I will check on this.

> Also for some reason it shows the duration is always 1 second more than on YouTube.

Might be something with how Youtube API returns the results, I don't see any problem with this though. I will see if this is happening with all songs and if so, I can subtract a second before showing the duration.

**Comment by Jipok** [comment] 2023-08-13 19:17
bump

**Comment by deepjyoti30** [comment] 2023-08-27 08:54
@Jipok The issue with the `plus` is fixed and will be included in the next release.

Regarding the seconds issue, I am unable to reproduce it on my end. Tried with the same results that you were seeing and I get correct seconds being shown so I will skip that one for now.

**Comment by deepjyoti30** [comment] 2023-08-27 09:13
Fix added in latest release.

**Closed by deepjyoti30** 2023-08-27 09:13 UTC
Labels: bug
