### ISSUE TITLE
Quite flag should disable all the output, otherwise dismissing output produces `Inappropriate ioctl for device`

### ISSUE THREAD

**Issue by quentincaffeino** [deepjyoti30/ytmdl#209] opened 2021-11-06 19:41 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2021.08.01`
- Youtube-dl version: `2021.06.06`

## How Ytmdl was installed?

`python3 -m pip install ytmdl`

## Console Log

```console
$ ytmdl -q --nolocal --level DEBUG --ignore-errors --artist 'Unquote' 'Cold Tenderness' > ./tmp

$ cat ./tmp
 ==> Logger running in DEBUG mode 
 ==> Passed args: Namespace(SONG_NAME=['Cold Tenderness'], quiet=True, song=None, choice=None, artist='Unquote', album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy=None, url=None, list=None, nolocal=True, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=True, title_as_name=False, level='DEBUG', disable_file=False, list_level=False) 
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> ['Cold Tenderness'] 
 ==> Cold Tenderness 
 ==> None 
 ==> proxy passed: None 
 ==> Passed format: mp3 
 ==> Quiet is enabled 
 ==> Searching Youtube for Cold Tenderness 
 ==> Downloading Unquote - Cold Tenderness (Original) in 320kbps 
 ==> Saving the files to: /home/quentincaffeino/.cache/ytmdl 
 ==> /home/quentincaffeino/.cache/ytmdl/Unquote#-#Cold#Tenderness#(Original).mp3 
 ==> ERROR: unable to download video data: [Errno 25] Inappropriate ioctl for device 
 ==> --ignore-errors passed. Skipping this song! 
```

## Description

So if I use ytmdl as a child process of my node program and it fails because of dynamic output it creates (`Inappropriate ioctl for device`). I just need it to download the file and I don't care about the choices or progress so `-q` should just do the job and don't bother me isn't it?

**Comment by deepjyoti30** [comment] 2021-11-07 06:07
@quentincaffeino Thanks for raising the issue.

The issue is not exactly from `ytmdl` but instead from a dependent package `downloader-cli` that ytmdl uses in order to show the progress of the downloads.

Working on a fix as we speak. This issue should be resolved in the next release!

**Comment by deepjyoti30** [comment] 2021-11-07 06:22
@quentincaffeino The above mentioned commit fixes the issue you were facing.

I have tested with the logs you provided and the patch fixes the issue. The song downloads properly. I am planning to add a release today itself so I will add these changes.

If you want you can test the commits or wait for the release!

**Closed** 2021-11-07 06:26 UTC
Labels: bug
