### ISSUE TITLE
Improve Metadata by using a different API (Spotify)

### ISSUE THREAD

**Issue by kiikoh** [deepjyoti30/ytmdl#158] opened 2021-02-02 23:47 UTC
# Feature Request

## Checklist

- [ x ] I've searched the bugtracker for similar feature requests including closed ones.
- [ x ] I will add the enhancement label to the issue.

## Description

Describe the feature

Currently, the metadata is not all that I was hoping for. I think implementing spotify's metadata will be the best. Users can create a free developer API key on their website.

**Comment by deepjyoti30** [comment] 2021-02-04 10:20
@kiikoh Usually the data provided by `itunes` is pretty much for most of the songs, the other providers just help sometimes when the song is not that famous.

Regarding `spotify`, other people have earlier suggested the use of it, however it's hard to add something like that especially because `Spotify` is mostly used for music streaming and since they need a premium account for the API. Anyhow, I think I can look into it and see if it'll be plausible to add Spotify as a provider.

**Comment by VicFic2006** [comment] 2021-05-31 11:56
You could look at how [spotdl](https://github.com/spotDL/spotify-downloader) implemented it.

**Comment by ThatGeekyWeeb** [comment] 2021-07-25 06:26
figured I would add to this since I've worked directly with the spotify api multiple times, there are certain api calls which do not require a premium account iirc, additionally I still have complete access to the api despite canceling my membership over the past month(s), as well as the fact that I am still able to use them from an account that has only ever been free, I believe that only the player SDK is premium only.

reading the spotify docs closer once more, I can confirm this to be true
(On web api DOCS site)
> To use the Web API, start by creating a Spotify user account (Premium or Free).

(On web playerback SDK DOCS site)
> You will need an access token from your personal Spotify Premium account

I have yet to work with python, but maybe I could be of some help,,

**Comment by deepjyoti30** [comment] 2021-07-26 10:08
@ThatGeekyWeeb Thanks for the heads up. I was actually considering adding this feature in the upcoming release and was aiming to test some code with the API.

I took a look at `spotdl`'s code and turns out they are providing a client ID and secret of their own that is being used by everyone who's using the app.

I was considering going that way and creating client ID and secret of my own for `ytmdl`. However, I'll check if the API works without authentication, in which case, it will be much easier to add support for metadata from `Spotify`.

**Comment by deepjyoti30** [comment] 2021-07-26 12:23
@kiikoh @VicFic2006 @ThatGeekyWeeb I'm happy to announce that Spotify support will be available from the next release.

If you're interested you can pull the latest commits from the `unstable` branch, install and use it yourself.

Support was added in 5a2f58e

**Comment by ThatGeekyWeeb** [comment] 2021-07-26 20:13
thank you! I'll test it right away!

**Comment by ThatGeekyWeeb** [comment] 2021-07-26 20:47
There should be a config option to change the country selected for the `market` opt, otherwise it seems to work!

**Comment by deepjyoti30** [comment] 2021-07-27 04:06
@ThatGeekyWeeb I'll see if the library has an option like that while searching. I understand that will beneficial and we already allow something similar for Itunes by passing the `ITUNES_COUNTRY` flag so this shouldn't be much hard if the API already supports that!

**Comment by deepjyoti30** [comment] 2021-07-27 12:24
@ThatGeekyWeeb I have added support for the `SPOTIFY_COUNTRY` feature. You can take a look at 62ad5b55088ead9a0edc47c115c54f64770b29d2

**Comment by ThatGeekyWeeb** [comment] 2021-07-27 16:00
That works great! It might be smart to add a command line opt that allows providing the ID of a track; as seen here
> https://developer.spotify.com/console/get-track/

**Comment by ThatGeekyWeeb** [comment] 2021-07-27 16:03
Much like `--itunes-id`, something like `--spotify-id` would be useful because searching for songs doesn't work sometimes due to license causing various issues with who the main artist is listed as

**Comment by deepjyoti30** [comment] 2021-07-30 14:09
@ThatGeekyWeeb Thanks for the suggestion, I'm thinking of adding that in the next iteration!

**Comment by deepjyoti30** [comment] 2021-07-30 14:46
@ThatGeekyWeeb Added support for `--spotify-id`. You can try it out if you want. Refer to 79f57b1fd27

I'll add an official release in a few days!

**Comment by ThatGeekyWeeb** [comment] 2021-07-30 20:05
I would recommend tweaking the api to use 300x300 for the image size for the cover art, unless theres a config for that; if not one for such might be useful, otherwise works perfectly! even able to grab removed songs thanks to the ID flag now!

**Comment by deepjyoti30** [comment] 2021-07-31 06:53
@ThatGeekyWeeb It already uses the best possible quality provided by Spotify. Also, it's not possible to switch the quality through the URL!

**Comment by ThatGeekyWeeb** [comment] 2021-07-31 11:52
well unless @kiikoh feels anything is missingm I think the spotify imp works great!

**Comment by kiikoh** [comment] 2021-07-31 14:22
I will check it out soon... Kinda new to this open-source stuff. Glad the feature was implemented

**Comment by deepjyoti30** [comment] 2021-08-01 09:28
@kiikoh @ThatGeekyWeeb Added in the latest release.

You can create new issues if you find any regarding Spotify. I'll close this since the feature is now added!

**Closed by deepjyoti30** 2021-08-01 09:28 UTC
Labels: enhancement
