### ISSUE TITLE
Using youtube url as search keywords, hence not finding result

### ISSUE THREAD

**Issue by amrit073** [deepjyoti30/ytmdl#233] opened 2022-05-18 06:14 UTC
# Bug report

## Checklist

- [+] I have searched for similar bugs in the issues.
- [+] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2022.03.16`
- Youtube-dl version: not installed

## How Ytmdl was installed?
pip

## Console Log

```console
download] Destination: /home/amrit/.cache/ytmdl/Hey#Jude#-#The#Beatles#-#Cover#by#Emily#Linge.mp3
[download] 100% of 4.46MiB in 00:00
 ==> Downloaded! 
[youtube] Xutz8QkN1NQ: Downloading webpage
[youtube] Xutz8QkN1NQ: Downloading android player API JSON
 ==> [{}] 
 ==> song_name:  Hey Jude - The Beatles - Cover by Emily Linge  song_meta:  https://www.youtube.com/watch?v=Xutz8QkN1NQ
 ==> None 
 ==> None:None 
 ==> Skip Meta: False 
 ==> Getting song data for https://www.youtube.com/watch?v=Xutz8QkN1NQ... 
 ==> Searching metadata with gaana 
 ==> Searching metadata with itunes 
 ==> No results found with the keyword https://www.youtube.com/watch?v=Xutz8QkN1NQ 
 ==> Something went wrong with iTunes. The program will continue withthe other providers. Please check '[/home/amrit/.cache/ytmdl/logs/log.cat]' for more details.             
 ==> Searching metadata with spotify 
 ==> Using US for Spotify country 
 ==> ext: mp3 
 ==> Moving to: /home/amrit/Music 
 ==> Moved to /home/amrit/Music... 
 ==> Done 
```

## Description
No results found with the keyword https://www.youtube.com/watch?v=Xutz8QkN1NQ 
Shouldn't it search with song name as keyword instead of youtube link?

**Comment by deepjyoti30** [comment] 2022-06-05 13:57
@amrit073 Thanks for reporting this issue. This is indeed a bug. The ideal behaviour is that the extracted name would be used to search for the metadata.

**Comment by deepjyoti30** [comment] 2022-06-05 14:23
@amrit073 Correction:

Not a bug actually. This was never considered. We do support automatic title extraction for songs in a playlist or songs that have chapters but when URL is passed, the song name is not extracted.

This, however, should be a feature. I will mark it as an enhancement and get it added in the next release.

**Comment by deepjyoti30** [comment] 2022-06-05 14:56
@amrit073 This feature is added as of f6fcb2a

I am closing this for now. You can test the above commit. If you find any issues, you can reopen this issue or comment here.

**Closed by deepjyoti30** 2022-06-05 14:56 UTC
Labels: enhancement
