### ISSUE TITLE
Crash on ampersand in artist

### ISSUE THREAD

**Issue by oliversalzburg** [deepjyoti30/ytmdl#290] opened 2023-12-26 08:52 UTC
# Bug report

## Checklist

- [X] I have searched for similar bugs in the issues.
- [X] I will add the bug label to this issue.

## Version Info

- Ytmdl version: latest
- Youtube-dl version: `PUT VERSION HERE`

## How Ytmdl was installed?

pip

## Console Log

```console
 ==> Enter Choice (1): -2
 ==> Amending the search because -2 was entered as the option
 ==> Enter new title to search metadata with (Surrender): surrender dead wax
 ==> Getting song data for surrender dead wax...
 ==> Setting data...
 ==> Choose One (Enter -1 to skip metadata or -2 to amend search)
 [1] Surrender by DEAD WAX
 [2] Surrender by DEAD WAX & MC Mota
 [3] Surrender by DEAD WAX & MC Mota
 ==> Enter Choice (1): 2
 ==> Preparing the album cover
 ==> ================================
 ==> Error occurred:   . Exiting. Pass `--ignore-errors` if you want errorslike this to be ignored
```

## Description

Looks like https://github.com/deepjyoti30/ytmdl/blob/master/ytmdl/dir.py#L15 could use a lot more love.

**Comment by deepjyoti30** [comment] 2024-04-14 13:14
Hi @oliversalzburg I am unable to reproduce the issue but I do agree that that bit of code could use some improvements. My guess is that you faced the issue because you are using the artist name in the final song name (configured through the config file?). I am going ahead with some improvements for this regardless.

**Comment by deepjyoti30** [comment] 2024-04-14 13:21
Should be fixed in the latest release. Feel free to re-open this if the issue is not fixed!

**Closed by deepjyoti30** 2024-04-14 13:21 UTC
Labels: bug
